services:
  nginx:
    image: nginx:1.26
    container_name: discuz_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/env.conf:/etc/nginx/conf.d/env.conf:ro
      - ./acme-certs:/etc/acme-certs:ro
      - ./dummy-certs:/etc/nginx/ssl:ro
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - discuz_net

  backend:
    container_name: royale-arena-backend
    build: 
      context: ./backend/royale-arena-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/royale-arena-backend:/app
      - /app/target
    environment:
      - RUST_LOG=debug
    command: cargo watch -x run
    networks:
      - discuz_net

  frontend:
    container_name: royale-arena-frontend
    build:
      context: ./frontend/royale-arena-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/royale-arena-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    networks:
      - discuz_net

networks:
  discuz_net:
    driver: bridge